server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    charset utf-8;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location /bundles/ {
        alias /var/www/html/public/bundles/;
        access_log off;
        expires max;
    }

    location /generated-ai/ {
        alias /var/www/html/public/generated-ai;
        access_log off;
        expires max;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|woff2?|eot|ttf|otf)$ {
        try_files $uri =404;
        access_log off;
        expires max;
    }

    location ^~ /.well-known/mercure {
        proxy_pass https://mercure-hub-op6e.onrender.com;  # URL publique du service Mercure
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        chunked_transfer_encoding off;
        proxy_read_timeout 3600s;

        # CORS
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";

        # Link header pour JS clients Mercure
        add_header Link "</.well-known/mercure>; rel=mercure";
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param HTTPS off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    error_page 404 /index.php;
    error_page 500 502 503 504 /index.php;
}
