;/etc/supervisor/conf.d/mercure.conf
[program:dunglas-mercure]
command=SERVER_NAME='http://127.0.0.1:3000' MERCURE_PUBLISHER_JWT_KEY='!ChangeThisMercureHubJWTSecretKey!' MERCURE_SUBSCRIBER_JWT_KEY='!ChangeThisMercureHubJWTSecretKey!' /usr/local/bin/mercure run --config /etc/mercure/dev.Caddyfile
numprocs=2
startsecs=0
autostart=true
autorestart=true
startretries=3
