; Supervisor main config

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

; Programs
[program:php-fpm]
command=/usr/sbin/php-fpm8.2 -F
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.err

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err

; Messenger consumer is disabled because we use sync://
;[program:messenger-consume]
;command=php /var/www/html/bin/console messenger:consume async --env=prod --time-limit=3600 --memory-limit=128M -vv
;user=root
;numprocs=1
;autostart=false
;autorestart=false
;stdout_logfile=/var/log/messenger.log
;stderr_logfile=/var/log/messenger.err.log

[include]
files = /etc/supervisor/conf.d/*.conf
