api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    use_symfony_listeners: true
    enable_swagger_ui: false
    enable_re_doc: false
