nelmio_api_doc:
    documentation:
        info:
            title: ORBIXUP API
            description: This is the API documentation for the ORBIXUP project.
            version: 0.0.1
    areas: # to filter documented areas
        default:
            path_patterns: ["^/api"]
