controllers:
    name_prefix: api_
    prefix: /api
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login

connect_google_start:
    path: /connect/google
    controller: App\Controller\SecurityController::connectGoogle

connect_google_check:
    path: /connect/google/check

home_page:
    path: /
    controller: App\Controller\HomeController::home
