controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    exclude: ../src/Controller/Api/
    type: attribute

api_controllers:
    name_prefix: api_
    prefix: /api
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute

api_login_check:
    path: /api/login

connect_google_start:
    path: /connect/google
    controller: App\Controller\SecurityController::connectGoogle

connect_google_check:
    path: /connect/google/check

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
