<?php

namespace App\Services\VisualIdentity;

use App\Entity\Auth\Client;
use App\Request\Branding\ColorPaletteGenerationRequest;
use App\Request\Branding\TypographieGenerationRequest;
use App\Request\Branding\VisualIdentityRequest;
use Symfony\Component\HttpFoundation\Request;

interface VisualIdentityServiceInterface
{
    /**
     * Generate Color Palettes from AI.
     */
    public function generateColorPalettes(ColorPaletteGenerationRequest $request): array;

    /**
     * Generate Typographies from AI.
     */
    public function generateTypographies(TypographieGenerationRequest $request): array;

    /**
     * Submit Color Palettes that is generated by AI.
     */
    public function submitColorPalette(Request $request): Client;

    /**
     * Submit typographie that is generated by AI.
     */
    public function submitTypographie(VisualIdentityRequest $request): Client;
}
