name: CI

on:
    push:
        branches: ["preprod", "prod"]
    pull_request:
        branches: ["preprod", "prod"]
    workflow_dispatch:

jobs:
    quality-check:
        runs-on: ubuntu-latest

        env:
            APP_ENV: test
            DATABASE_URL: sqlite:///%GITHUB_WORKSPACE%/var/test.db
            JWT_PASSPHRASE: testpass

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl, pdo, pdo_pgsql, pgsql, sqlite3, pdo_sqlite
                  coverage: none

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress

            - name: Generate JWT keys for tests
              run: |
                  mkdir -p config/jwt
                  openssl genrsa -out config/jwt/private.pem -aes256 -passout pass:testpass 4096
                  openssl rsa -pubout -in config/jwt/private.pem -passin pass:testpass -out config/jwt/public.pem

            - name: Create SQLite test DB
              run: |
                  rm -f var/test.db
                  mkdir -p var
                  touch var/test.db

            - name: Create schema
              run: php bin/console doctrine:schema:create --env=test --no-interaction --no-debug

            - name: Validate DB schema
              run: php bin/console doctrine:schema:validate --env=test --no-interaction --no-debug

            - name: Run PHP CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --memory-limit=512M

            - name: Run PHPUnit
              run: vendor/bin/phpunit --testdox
